# Generated by Django 5.1.1 on 2024-09-28 19:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_alter_usernote_note_alter_usernote_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usernote',
            unique_together={('user', 'note')},
        ),
    ]
